# Data Structure

## List
- 1D
- Heterogeneous
- Duplicate values
- Indexing & slicing
- Mutable

In [1]:
empty_cart=[]
type(empty_cart)

list

In [4]:
items_to_buy = ["Apple","orange","banana","Apple","pomgranite","grapes",6,8.9,4]
print(f'{items_to_buy[0]}')
print(f'{items_to_buy[-1]}')
print(f'{items_to_buy[5]}')
print(f'{items_to_buy[0:2]}')
print(f'{items_to_buy[-7:-4]}')
print(f'{items_to_buy[:4]}')
print(f'{items_to_buy[:5:2]}') # interval of 2
print(f'{items_to_buy[::-1]}') # interval -1 indicate reverse order
items_to_buy[4]="Pomogranites"
print(f'{items_to_buy}')

Apple
4
grapes
['Apple', 'orange']
['banana', 'Apple', 'pomgranite']
['Apple', 'orange', 'banana', 'Apple']
['Apple', 'banana', 'pomgranite']
[4, 8.9, 6, 'grapes', 'pomgranite', 'Apple', 'banana', 'orange', 'Apple']
['Apple', 'orange', 'banana', 'Apple', 'Pomogranites', 'grapes', 6, 8.9, 4]

In [14]:
print(f'items_to_buy before clear: {items_to_buy}')
items_to_buy.clear() # clear all the values in list
print(f'items_to_buy after clear: {items_to_buy}')
items_to_buy = ["dragon","blueberry","avacoda","blueberry",6,8.9,4]
print(f'new items_to_buy: {items_to_buy}')
new_copy=items_to_buy.copy()
new_copy.append("pear")
print(f'after copy function: {new_copy} of items_to_buy: {items_to_buy}')
print(f'count of items to buy: {items_to_buy.count("blueberry")}')
new_list=["fruits","vegetables","groceries"]
items_to_buy.extend(new_list)
print(f'items to buy extend: {items_to_buy}')
print(f'index of fruits in items to buy: {items_to_buy.index("fruits")}')
items_to_buy.insert(3, "new_fruit")
print(f'items to buy after insert: {items_to_buy}')
removd_item = items_to_buy.pop()
print(f'removed item: {removd_item}')
items_to_buy.remove("blueberry")
print(f'items to buy after remove: {items_to_buy}')
items_to_buy.reverse()
print(f'items to buy after reverse: {items_to_buy}')
new_list.sort()
print(f'new_list after sort: {new_list}')

items_to_buy before clear: ['vegitables', 'fruits', 4, 8.9, 6, 'blueberry', 'new_fruit', 'avacoda', 'dragon']
items_to_buy after clear: []
new items_to_buy: ['dragon', 'blueberry', 'avacoda', 'blueberry', 6, 8.9, 4]
after copy function: ['dragon', 'blueberry', 'avacoda', 'blueberry', 6, 8.9, 4, 'pear'] of items_to_buy: ['dragon', 'blueberry', 'avacoda', 'blueberry', 6, 8.9, 4]
count of items to buy: 2
items to buy extend: ['dragon', 'blueberry', 'avacoda', 'blueberry', 6, 8.9, 4, 'fruits', 'vegetables', 'groceries']
index of fruits in items to buy: 7
items to buy after insert: ['dragon', 'blueberry', 'avacoda', 'new_fruit', 'blueberry', 6, 8.9, 4, 'fruits', 'vegetables', 'groceries']
removed item: groceries
items to buy after remove: ['dragon', 'avacoda', 'new_fruit', 'blueberry', 6, 8.9, 4, 'fruits', 'vegetables']
items to buy after reverse: ['vegetables', 'fruits', 4, 8.9, 6, 'blueberry', 'new_fruit', 'avacoda', 'dragon']
new_list after sort: ['fruits', 'groceries', 'vegetables']

## Set
- 1D
- Heterogeneous
- No Duplicate values
- mutable
- No Indxing & Slicing

In [33]:
empty_cart = set()
type(empty_cart)
items_to_buy_2 = {"Apple","orange","banana","Apple","pomgranite","grapes",6,8.9,4}
print(f'{items_to_buy_2}')
print(f'type of item to buy 2: {type(items_to_buy_2)}')
copy_items=items_to_buy_2.copy()
copy_items.add("new_item")
print(f'after adding new value to copy item: {copy_items} and orginal items to buy2 is: {items_to_buy_2}')
new_items={"dragon","pear","Apple"}
diff=items_to_buy_2.difference(new_items)
print(f'difference: {diff} an original items to buy2: {items_to_buy_2}')
items_to_buy_2.difference_update(new_items)
print(f'difference update of the items to buy2: {items_to_buy_2}')
items_to_buy_2.discard("pear")
print(f'discard function - items to buy2: {items_to_buy_2}')
# items_to_buy_2.remove("pear") # it will fail as there is no pear value in the set
items_to_buy_2.remove("orange")
print(f'remove function - items to buy2: {items_to_buy_2}')

print(f'is disjoint of {items_to_buy_2.isdisjoint(new_items)}')
print(f'issubset of {items_to_buy_2.issubset(copy_items)}')
print(f'issuperset of {items_to_buy_2.issuperset(new_items)}')
last_value = items_to_buy_2.pop()
print(f'last value from items using pop: {last_value}')
sym_items=items_to_buy_2.symmetric_difference(new_items)
print(f'symmetric_difference of items to buy2 with new_items: {sym_items}')
items_to_buy_2.symmetric_difference_update(new_items)
print(f'symmetric_difference_upte of items to buy2 with new_items: {items_to_buy_2}')

new_intersection=items_to_buy_2.intersection(new_items)
print(f'intersection of items to buy2 an new_items: {new_intersection}')
items_to_buy_2.intersection_update(new_items)
print(f'intersection update of items to buy2 an new_items: {items_to_buy_2}')

union_items = items_to_buy_2.union({"mango","kiwi"})
print(f'union_items of items to buy2 : {union_items}')
items_to_buy_2.update({"mango","kiwi"})
print(f'update to items to buy2 : {items_to_buy_2}')
items_to_buy_2.clear()
print(f'after clear of items to buy2 : {len(items_to_buy_2)}')

{4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange', 'Apple'}
type of item to buy 2: <class 'set'>
after adding new value to copy item: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange', 'Apple', 'new_item'} and orginal items to buy2 is: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange', 'Apple'}
difference: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange'} an original items to buy2: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange', 'Apple'}
difference update of the items to buy2: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange'}
discard function - items to buy2: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana', 'orange'}
remove function - items to buy2: {4, 'pomgranite', 6, 'grapes', 8.9, 'banana'}
is disjoint of True
issubset of True
issuperset of False
last value from items using pop: 4
symmetric_difference of items to buy2 with new_items: {'dragon', 'pomgranite', 6, 'grapes', 8.9, 'pear', 'banana', 'Apple'}
symmetric_difference_upte of items to buy2 with new_items: {'dragon', 'pomgranite', 6, 'grapes', 8.9, 'banana', 'pear', 'Apple'}
intersection of items to buy2 an new_items: {'Apple', 'pear', 'dragon'}
intersection update of items to buy2 an new_items: {'Apple', 'pear', 'dragon'}
union_items of items to buy2 : {'Apple', 'kiwi', 'dragon', 'mango', 'pear'}
update to items to buy2 : {'Apple', 'kiwi', 'dragon', 'mango', 'pear'}
after clear of items to buy2 : 0

## Tuple
- 1D
- Heterogeneous
- Duplicate value allowed
- Indexing and slicing
- immutable

In [38]:
empty_tuple=()
print(f'{empty_tuple}')
items_to_buy_3 = ("Apple","orange","banana","Apple","pomgranite","grapes",6,8.9,4)
print(f'{items_to_buy_3}')
type(items_to_buy_3)
print(f'{items_to_buy_3[0]}')
print(f'{items_to_buy_3[-1]}')
print(f'{items_to_buy_3[0:2]}')
print(f'count of Apple: {items_to_buy_3.count("Apple")}')
print(f'index of Apple: {items_to_buy_3.index("Apple")}')

()
('Apple', 'orange', 'banana', 'Apple', 'pomgranite', 'grapes', 6, 8.9, 4)
Apple
4
('Apple', 'orange')
count of Apple: 2
index of Apple: 0

## Dictionary
- key:value pair
- 2D
- Heterogeneous
- Mutable
- Indexing & slicing is not possible
- Don't create Duplicate key, but you can create Duplicate values

In [73]:
vegetables={"Apple":3,"Orange":2,"Onion":5}
print(f'values of vegitables:{vegetables.values()}')
print(f'keys of vegitables:{vegetables.keys()}')

dict1=vegetables.copy()
print(f'copy of vegitables:{dict1}')
list1=["Tomato","beans"]
list2 = [3,4]
dict2 = dict.fromkeys(list1,2)
print(f'new dictionary from list: {dict2}')
print(f'vlue of the APPLE : {vegetables.get("Apple")}')
print(f'get key an values in dictionary: {vegetables.items()}')

print(f'pop Orange in dictionary: {vegetables.pop("Orange")}, current Dictionary:{vegetables}')
print(f'pop Orange in dictionary: {vegetables.popitem()}, current Dictionary:{vegetables}')
print(f'setdefault function: {vegetables.setdefault("Apple", 10)},, current Dictionary:{vegetables}')
print(f'setdefault function: {vegetables.setdefault("Onion", 5)}, current Dictionary:{vegetables}')
new_dict={"carrot":2, "beetroot":1}
vegetables.update(new_dict)
print(f'updated Dictionary:{vegetables}')
vegetables.clear()
print(f'after clear vegetables:{vegetables}')

values of vegitables:dict_values([3, 2, 5])
keys of vegitables:dict_keys(['Apple', 'Orange', 'Onion'])
copy of vegitables:{'Apple': 3, 'Orange': 2, 'Onion': 5}
new dictionary from list: {'Tomato': 2, 'beans': 2}
vlue of the APPLE : 3
get key an values in dictionary: dict_items([('Apple', 3), ('Orange', 2), ('Onion', 5)])
pop Orange in dictionary: 2, current Dictionary:{'Apple': 3, 'Onion': 5}
pop Orange in dictionary: ('Onion', 5), current Dictionary:{'Apple': 3}
setdefault function: 3,, current Dictionary:{'Apple': 3}
setdefault function: 5, current Dictionary:{'Apple': 3, 'Onion': 5}
updated Dictionary:{'Apple': 3, 'Onion': 5, 'carrot': 2, 'beetroot': 1}
after clear vegetables:{}

# Task Dataframe

## Dataframe1

In [83]:
import pandas as pd
list1=["Apple","Orange","Banana"]
fruits_dict={"fruits":list1}
pd.DataFrame(fruits_dict)

   fruits
0   Apple
1  Orange
2  Banana

## Dataframe2

In [85]:
set1={"Carrot","onion","tomato","potato"}
veg_dict={"Vegetables":list(set1)}
pd.DataFrame(veg_dict)

  Vegetables
0     Carrot
1     tomato
2      onion
3     potato

## Dataframe3

In [92]:
list1=["Apple","Orange","Banana","Kiwi"]
set1={"Carrot","onion","tomato","potato"}
pd.DataFrame({"fruits":list1,"vegetables":tuple(set1)})

   fruits vegetables
0   Apple     Carrot
1  Orange     tomato
2  Banana      onion
3    Kiwi     potato

In [97]:
list1=["Apple","Orange","Banana"]
set1={"Carrot","onion","tomato","potato","beetroot"}
if len(list1) > len(set1):
    shortage = len(list1) - len(set1)
    for i in range(0,shortage):
        set1.add("none")
elif len(list1) < len(set1):
    shortage = len(set1) - len(list1)
    for i in range(0,shortage):
        list1.append("none")
pd.DataFrame({"fruits":list1,"vegetables":list(set1)})

   fruits vegetables
0   Apple     tomato
1  Orange   beetroot
2  Banana     Carrot
3    none     potato
4    none      onion